### PR TITLE
Migrate permissions on static bucket to a bucket policy

### PR DESCRIPTION
**Pull request by lpsinger**
Use a bucket policy instead of per-object ACLs to set permissions on objects in the static bucket. Previously, the per-object ACLs were [hard coded]. By setting the permissions in the CloudFormation document, they can now be customized by macros.

According to the [AWS S3 docs], bucket owner enforced policies are recommended over per object ACLs anyway.

See also architect/deploy#350.

[hard coded]: https://github.com/architect/deploy/blob/v3.1.1/src/static/publish/s3/put-files/put-params.js#L9
[AWS S3 docs]: https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html

### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [x] Summarized your changes in `changelog.md`
- [x] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by lpsinger** [comment]
> * [ ]  Summarized your changes in `changelog.md`

Under what version should I put my changelog entry?

**Comment by ryanblock** [comment]
Whatever is fine, Arc 10 is about to bump the major, I’ll edit it then if we merge.

One thing Arc supports is S3-only deployments. So you can ship @static without @http, and serve a static page directly from an S3 bucket. Would this change break that?

**Comment by lpsinger** [comment]
> Whatever is fine, Arc 10 is about to bump the major, I’ll edit it then if we merge.

OK, shall I add an arc 10 section to the changelog?

> One thing Arc supports is S3-only deployments. So you can ship `@static` without `@http`, and serve a static page directly from an S3 bucket. Would this change break that?

It shouldn't. This should be functionally the same as applying `public-read` to every single file in the bucket.

Note, I haven't tested this live yet on AWS to make sure that the policy document is correct. I'm working on that now, though.

**Comment by lpsinger** [comment]
> Note, I haven't tested this live yet on AWS to make sure that the policy document is correct. I'm working on that now, though.

Just tested. Works like a charm!

**Comment by ryanblock** [comment]
Did some testing this morning, I couldn't find any issues. This should make it into Arc 10!

**Comment by lpsinger** [comment]
Cool, thank you!

**Comment by ryanblock** [comment]
Thank you for your patience! We try not to let PRs sit that long; as I mentioned in Discord, CloudFormation changes are treated very seriously, as they have the potential to do a lot of inadvertent harm!

**Pull request merged**
