### PR TITLE
Add support for dynamodb encryption

### PR DESCRIPTION
**Pull request by defionscode**
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [x] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [x] Summarized your changes in `changelog.md`
- [x] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

Fixes https://github.com/architect/architect/issues/584
Doc updates https://github.com/architect/arc.codes/pull/183

### CODE REVIEW

**Comment by brianleroux** [comment]
this is great, thx! 👍

**Comment by ryanblock** [comment]
Yo, this is exciting. Should we have something in Architext that also creates / manages the KMS master key? Cc @brianleroux

**Comment by brianleroux** [comment]
Published in `@architect/architect@6.1.1`! 

We've been asked about KMS a few times for a few different things ya. Def into it. I love KMS. (We have this thing too https://github.com/smallwins/keystash)

**Comment by austinkelleher** [comment]
I think if a user is storing secrets, they should use AWS Secrets Manager instead of encrypting using KMS and storing in S3. Thoughts @brianleroux?

**Comment by brianleroux** [comment]
As usual, it depends. KMS is like having a personal safe. Maybe you need that. Maybe you're doing something a little less intense and don't want to pay for storing hack project API keys. Generally think the open source project should stay safely within the AWS free tier by default and use macros and personal enterprise to monetize aspects like compliance, security and best practice performance CI/CD. ;)

**Pull request merged**
